<?php
    /**
     * Copyright © Magento, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */
    
    /* @var $block \Magento\Cms\Block\Widget\Block */
    $ids = $this->getIdentities()[1];
    $arrIds = explode("_", $ids);
    $class = $arrIds[2];
?>
<div class="widget block block-static-block <?= /* @noEscape */ $class ?>">
    <?= /* @noEscape */ $block->getText() ?>
</div>
