<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) :
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
?>
<li class="authorization-link logout">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        Logout
    </a>
</li>

<?php 
    else :
?>
<li class="authorization-link login">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <i class="fas fa-user"></i>
    </a>
</li>
<?php endif ?>

